version: '3.9'

services:
  db_ps:
    image: mariadb:10.2
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  prestashop:
    hostname: prestashop
    healthcheck:
      test: curl --fail http://localhost:9999 || exit 1
      timeout: 5s
      interval: 10s
      retries: 10
    build:
      context: ./
      dockerfile: ./Dockerfile
    links:
      - db_ps
    depends_on:
      - db_ps
    ports:
      - "9999:9999"
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      DB_CREATE: ${DB_CREATE}
      DB_CLEAR: ${DB_CLEAR}
