name: Build and check

on: [push]

jobs:
  build-prestashop:
    runs-on: ubuntu-latest
#    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: docker-compose build
      - name: docker-compose up
        run: docker-compose --env-file env/.env.dev up -d
      - name: wait for install
        run: sleep 60 # Need to figure out how to check that
      - name: healthcheck
        run: docker-compose exec --no-TTY prestashop curl --fail http://localhost:9999
      - name: teardown
        run: docker-compose down -v --remove-orphans