name: Build and check

on: [push]

jobs:
  build-prestashop:
#    runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: docker-compose up
        run: docker-compose --env-file .env.dev up -d
      - name: healthcheck
        run: docker-compose exec prestashop curl --fail http://localhost:9999
